version: 2

models:
  - name: fct_disparos
    description: "Tabela fato consolidada para o dashboard de CRM"
    columns:
      - name: session_id
        tests:
          - unique
          - not_null
      - name: nm_template
        description: "Nome da campanha disparada"
        tests:
          - accepted_values:
              values: ['crm_cerebro_ads_apple_1903', 'crm_cerebro_galaxys26']
              quote: true